fixed compatibility
owncloudarchive/bookmarks pull request #3
Opened 2017-03-09 15:20 UTC by Kawohl

Fixed some changes that stopped compatibility with ownCloud 10

2017-05-17 02:18 UTC, linkp commented
Is there anything I can do to help get this PR merged? This is the last ownCloud app I need to have working again after an unexpected upgrade to ownCloud 10.0.0.

2017-05-26 06:06 UTC, vkzunited commented
Thank you Kawohl , the fixes worked to get ocX running :)

2017-08-03 07:57 UTC, ghost requested changes
There is an syntax error in the search.php change (opening bracket)

2017-08-07 10:05 UTC, ghost approved these changes

2017-08-07 10:09 UTC, merged